/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/sidebars/PCSidebar copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MobileSidebar: typeof import('./src/components/sidebars/MobileSidebar.vue')['default']
    PCSidebar: typeof import('./src/components/sidebars/PCSidebar.vue')['default']
    PCSidebar2: typeof import('./src/components/sidebars/PCSidebar2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/sidebars/SidebarMenu.vue')['default']
  }
}
